# Override some built-in rules.
config:
  default: true

  # This should match `printWidth` in `.prettierrc.yaml`.
  line-length:
    line_length: 100

  # The same headline in different nested sections is okay (and necessary for
  # CHANGELOG.md).
  no-duplicate-heading:
    allow_different_nesting: true

# Fix any fixable errors.
fix: true

# Disable inline config comments.
noInlineConfig: true

# Disable progress on stdout (only valid at root).
noProgress: true
