overrides:
  - files:
      - "**/*.yaml"
    options:
      tabWidth: 2
      # In double quotes you can use escapes.
      singleQuote: false
  - files:
      - "**/*.md"
    options:
      printWidth: 100
      proseWrap: always
