default_stages:
  # Prevent that hooks run twice, triggered by both
  # the Git commit-msg and the pre-commit hook.
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.15.0
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: [--ignore-words=.codespellignore]
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.29.4
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or:
          - markdown
          - yaml
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: [--all, --]
      - id: clippy
        name: clippy --all-features
        args: [--locked, --all-features, --all-targets, --, -D, warnings]
      - id: clippy
        name: clippy --no-default-features
        args: [--locked, --no-default-features, --all-targets, --, -D, warnings]
  - repo: local
    hooks:
      - id: cargo-doc
        name: cargo-doc
        entry: env RUSTDOCFLAGS=-Dwarnings cargo
        language: system
        pass_filenames: false
        args: [doc, --locked, --no-deps, --all-features]
