# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: publish-release

permissions:
  contents: read

on:
  push:
    tags:
      # Only match release version tags
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: short

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # Check out the repository before the remaining steps that depend on it.
      # All preceding steps are independent of the repository contents.
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Publish release on creates.io
        env:
          API_TOKEN: ${{ secrets.CRATES_IO_PUBLISH_UPDATE_TOKEN }}
        run: >-
          cargo publish --token ${API_TOKEN}
